### ISSUE TITLE
Imagem repetida na pagina de login

### ISSUE THREAD

**Issue by WallysFerreira** [Thiago-Mota-Santos/pagarmepix#24]
Percebi que a imagem na esquerda repete e fica um pouco confuso
![image](https://github.com/Thiago-Mota-Santos/pagarmepix/assets/105322824/c3e05dfe-5154-404c-8613-e0afbf8d540a)

Acredito que se deixar uma vez só centralizada ficaria mais clean
![image](https://github.com/Thiago-Mota-Santos/pagarmepix/assets/105322824/1ac3d13b-0e86-45b6-bc8f-4e29aa4a3a2f)

Se julgarem útil eu posso implementar isso

**Comment by Thiago-Mota-Santos** [comment]
Uma pessoa fez um pr tirando a repetição e agora eu dei um ajuste no tamanho da imagem. Parece que tá dando um bo com o deploy da vercel, mas logo mais deve estar tudo funcionando ok
