### ISSUE TITLE
Add email/password authentication using firebase

### ISSUE THREAD

**Issue by Thiago-Mota-Santos** [Thiago-Mota-Santos/pagarmepix#28]
![image](https://github.com/Thiago-Mota-Santos/pagarmepix/assets/75326612/e43d8fa0-1d65-4442-90eb-b50204898abe)

fields email/password: 

![image](https://github.com/Thiago-Mota-Santos/pagarmepix/assets/75326612/131a795f-0918-41c5-b377-39f664b770b1)

![image](https://github.com/Thiago-Mota-Santos/pagarmepix/assets/75326612/cb613ca8-4583-4348-b1a1-7b9e2b2735c2)

**Comment by mateusmoov** [comment]
Can you assign me?
And it just a login and password and after communicate with the auth from firebase? No registration yet?

**Comment by sergiohdljr** [comment]
hey, can you assign me ?

**Comment by Thiago-Mota-Santos** [comment]
> hey, can you assign me ?
🫡
